### ISSUE TITLE
Error in the /miniannouncer toggle command

### ISSUE THREAD

**Issue by Anghelot** [devblook/miniannouncer#5]
It happens that when I try to toggle the minimessage, I get an error in the console. 

org.bukkit.command.CommandException: Unhandled exception executing 'miniannouncer toggle' in dev.triumphteam.cmd.bukkit.BukkitCommand(miniannouncer)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:178) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:981) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:321) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2339) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: dev.triumphteam.cmd.core.exceptions.CommandExecutionException: An error occurred while executing the command. On "miniannouncer" command on "toggle" sub command.
        at dev.triumphteam.cmd.core.AbstractSubCommand.lambda$execute$0(AbstractSubCommand.java:184) ~[MiniAnnouncer-2.3.0.jar:?]
        at dev.triumphteam.cmd.core.execution.SyncExecutionProvider.execute(SyncExecutionProvider.java:32) ~[MiniAnnouncer-2.3.0.jar:?]
        at dev.triumphteam.cmd.core.AbstractSubCommand.execute(AbstractSubCommand.java:180) ~[MiniAnnouncer-2.3.0.jar:?]
        at dev.triumphteam.cmd.bukkit.BukkitCommand.execute(BukkitCommand.java:107) ~[MiniAnnouncer-2.3.0.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 22 more
Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2768) ~[?:?]
        at java.util.Formatter.format(Formatter.java:2705) ~[?:?]
        at java.lang.String.format(String.java:4138) ~[?:?]
        at me.jonakls.miniannouncer.message.MessageHandler.getMessage(MessageHandler.java:40) ~[MiniAnnouncer-2.3.0.jar:?]
        at me.jonakls.miniannouncer.message.MessageHandler.sendMessage(MessageHandler.java:60) ~[MiniAnnouncer-2.3.0.jar:?]
        at me.jonakls.miniannouncer.command.MainCommand.toggle(MainCommand.java:36) ~[MiniAnnouncer-2.3.0.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at dev.triumphteam.cmd.core.AbstractSubCommand.lambda$execute$0(AbstractSubCommand.java:182) ~[MiniAnnouncer-2.3.0.jar:?]
        at dev.triumphteam.cmd.core.execution.SyncExecutionProvider.execute(SyncExecutionProvider.java:32) ~[MiniAnnouncer-2.3.0.jar:?]
        at dev.triumphteam.cmd.core.AbstractSubCommand.execute(AbstractSubCommand.java:180) ~[MiniAnnouncer-2.3.0.jar:?]
        at dev.triumphteam.cmd.bukkit.BukkitCommand.execute(BukkitCommand.java:107) ~[MiniAnnouncer-2.3.0.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 22 more
        
        
Any solution or if it's a plugin problem?

**Comment by jonakls** [comment]
Hello

Could you send me a copy or let me see how you have your configuration files?

**Comment by jonakls** [comment]
Hi, @Anghelot fixed [here](https://github.com/devblook/miniannouncer/releases/tag/2.4.0)

Thx for u report!
